sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

before_script:
  - sudo apt-get update
  - sudo apt-get install mysql

script:
  - vendor/bin/codecept run api