sudo: false

language: php

php:
  - 5.6

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer install
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'

script:
  - vendor/bin/codecept run api