sudo: false

language: php

services:
- mysql

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'

script:
  - vendor/bin/codecept run api